FROM balenalib/%%BALENA_MACHINE_NAME%%-python

# set a directory for our script
WORKDIR /usr/src/app

# copy our script over to new directly
COPY harvest.py /usr/src/app

# install dependencies
# RUN XYZ

# command for running the application
CMD ["python", "/usr/src/app/harvest.py"]